"""first migration

Revision ID: 8b28bc483f45
Revises:
Create Date: 2020-07-31 09:48:26.286368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b28bc483f45"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorias",
        sa.Column("ID", sa.BigInteger(), nullable=False),
        sa.Column("categoria", sa.VARCHAR(length=50), nullable=True),
        sa.PrimaryKeyConstraint("ID"),
    )
    op.create_table(
        "classificacao",
        sa.Column("ID", sa.BigInteger(), nullable=False),
        sa.Column("prioridade", sa.BigInteger(), nullable=True),
        sa.Column("nome", sa.VARCHAR(length=20), nullable=True),
        sa.Column("descritor", sa.Text(), nullable=True),
        sa.Column("tempo", sa.VARCHAR(length=100), nullable=True),
        sa.Column("cor_hex", sa.CHAR(length=6), nullable=True),
        sa.PrimaryKeyConstraint("ID"),
    )
    op.create_table(
        "registros_sinais",
        sa.Column("ID", sa.BigInteger(), nullable=False),
        sa.Column("id_qp", sa.BigInteger(), nullable=False),
        sa.Column("id_sinal", sa.BigInteger(), nullable=False),
        sa.Column("id_classificacao", sa.BigInteger(), nullable=False),
        sa.Column("min", sa.DECIMAL(precision=4, scale=1), nullable=True),
        sa.Column("max", sa.DECIMAL(precision=4, scale=1), nullable=True),
        sa.Column("descritor", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("ID"),
    )
    op.create_table(
        "registros_sintomas",
        sa.Column("ID", sa.BigInteger(), nullable=False),
        sa.Column("id_qp", sa.BigInteger(), nullable=True),
        sa.Column("id_classificacao", sa.BigInteger(), nullable=True),
        sa.Column("sintoma", sa.VARCHAR(length=125), nullable=True),
        sa.Column("descritor", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("ID"),
    )
    op.create_table(
        "sinais",
        sa.Column("ID", sa.BigInteger(), nullable=False),
        sa.Column("identificador", sa.VARCHAR(length=100), nullable=True),
        sa.Column("nome", sa.VARCHAR(length=100), nullable=True),
        sa.Column("unidade", sa.VARCHAR(length=20), nullable=True),
        sa.Column("descritor", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("ID"),
    )
    op.create_table(
        "sintomas",
        sa.Column("ID", sa.BigInteger(), nullable=False),
        sa.Column("sintoma", sa.VARCHAR(length=256), nullable=True),
        sa.Column("descritor", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("ID"),
    )
    op.create_table(
        "usuarios",
        sa.Column("ID", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.VARCHAR(length=256), nullable=True),
        sa.Column("senha", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("ID"),
    )
    op.create_table(
        "queixas_principais",
        sa.Column("ID", sa.BigInteger(), nullable=False),
        sa.Column("sintoma", sa.VARCHAR(length=256), nullable=True),
        sa.Column("observacao", sa.Text(), nullable=True),
        sa.Column("categoria", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["categoria"], ["categorias.ID"],),
        sa.PrimaryKeyConstraint("ID"),
    )
    op.create_table(
        "queixas_sinais_classificacao",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("fk_queixa", sa.BigInteger(), nullable=True),
        sa.Column("fk_sinal", sa.BigInteger(), nullable=True),
        sa.Column("fk_classificacao", sa.BigInteger(), nullable=True),
        sa.Column("min", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("max", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("descritor", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["fk_classificacao"], ["classificacao.ID"],),
        sa.ForeignKeyConstraint(["fk_queixa"], ["queixas_principais.ID"],),
        sa.ForeignKeyConstraint(["fk_sinal"], ["sinais.ID"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "queixas_sintomas_classificacao",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("fk_queixa", sa.BigInteger(), nullable=True),
        sa.Column("fk_sintoma", sa.BigInteger(), nullable=True),
        sa.Column("fk_classificacao", sa.BigInteger(), nullable=True),
        sa.Column("descritor", sa.Text(), nullable=True),
        sa.Column("tmp_sintoma", sa.VARCHAR(length=256), nullable=True),
        sa.ForeignKeyConstraint(["fk_classificacao"], ["classificacao.ID"],),
        sa.ForeignKeyConstraint(["fk_queixa"], ["queixas_principais.ID"],),
        sa.ForeignKeyConstraint(["fk_sintoma"], ["sintomas.ID"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("queixas_sintomas_classificacao")
    op.drop_table("queixas_sinais_classificacao")
    op.drop_table("queixas_principais")
    op.drop_table("usuarios")
    op.drop_table("sintomas")
    op.drop_table("sinais")
    op.drop_table("registros_sintomas")
    op.drop_table("registros_sinais")
    op.drop_table("classificacao")
    op.drop_table("categorias")
    # ### end Alembic commands ###
